### PR TITLE
Additional tests

### PR DESCRIPTION
**Pull request by joshua-hampton**
I have gone through the tests folder updating some functions and adding further checks. There are now more tests that run as intended - also updated the main github workflow to run all tests as they now (should) all work as intended (tested locally with Python 3.7 and 3.11).

### CODE REVIEW

**Comment by joshua-hampton** [comment]
Tests failed because the GitHub workflow needs the udunits-2 library installed

**Comment by agstephens** [comment]
@joshua-hampton: great work in adding more tests into the code-base!

**Comment by joshua-hampton** [comment]
I have adding the installation of udunits2 to the github action, so the cf-python module can now be imported and everything works.

**Comment by joshua-hampton** [comment]
Cancelling this PR to work on more tests with latest version of code.

**Pull request closed without merging**
